# Generated by Django 2.1.5 on 2019-08-07 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20190203_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='last_reservation_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
